### ISSUE TITLE
PySide2.QtCore has no attribute QString

### ISSUE THREAD

**Issue by TaigaOsguthorpe** [TaigaOsguthorpe/Image-db#13]
## Description of the issue:
(Development Branch) After commit df55a9994e98c1e959c5ac01e1ebda7412c79959, an `AttributeError` occurs whilst trying to run the program.

## System Info:
- OS: Linux Mint 19 Tara (64-bit)
- Python Version: 3.7.3
- PySide2/Qt Version: 5.12.3/5.13.0 (both where tested)
- Sqlite3 Version: 2.6.0
- SQLite Version: 3.22.0

## Error Message:
```
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    raise(error)
  File "main.py", line 12, in <module>
    _fromUtf8 = QtCore.QString.fromUtf8
AttributeError: module 'PySide2.QtCore' has no attribute 'QString'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    raise(error)
  File "main.py", line 12, in <module>
    _fromUtf8 = QtCore.QString.fromUtf8
AttributeError: module 'PySide2.QtCore' has no attribute 'QString'
```
## Possible solution:
Removing/commenting out the lines.
```python3
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError as error:
    raise(error)
```
This fix has only been tested on Linux so it is unknown/unclear if it will effect the program under the Windows operating system.

**Comment by TaigaOsguthorpe** [comment]
Issue seems to arises from commit 90e3fd1bd27770e674f60ba9f191eb738eda9373, `lines 13-15` in `main.py`.
These lines of code (lines 13-15) are from `PySide2-uic` so it is unclear if they are actually needed. Tests without them show no signs of anything going wrong with UTF-8 characters Kanji specific characters where tested.
I honestly do not know why this code was running fine with these lines of code before this commit.

**Closing due to fixed in b92f5139dab6129dfaa6442a53863ce2ec5cef93.**
